name: pennsieve-agent-python
channels:
    - conda-forge
dependencies:
    - make
    - compilers
    - python
    # pip
    #- pip=20.3.3 
    - pip:
        - grpcio
        - grpcio-tools
        - protobuf
