name: pennsieve-agent-python
channels:
    - conda-forge
dependencies:
    - make
    - compilers
    - python
    - grpcio
    - grpcio-tools
    
    # pip
    - pip=20.3.3 
    - pip:
        - grpc
