name: Reviewdog

on:
  pull_request:
    types: [opened, edited, synchronize, review_requested, reopened]

jobs:
  reviewdog:
    runs-on: ubuntu-latest

    if: github.event.action == 'opened' || github.event.requested_team.name == 'reviewdog'

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install
      run: |
        python -m pip install -U pip
        python -m pip install -U black
        python -m pip install -U blackdoc
        python -m pip install -U isort
        pip install --progress-bar off -U .[checking]
    - name: Apply formatters
      run: |
        black .
        blackdoc .
        isort .
    - name: Reviewdog
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: formatters
